name: hidden_drawer_menu
description: Hidden Drawer Menu is a library for adding a beautiful drawer mode menu feature with perspective animation
version: 1.1.2
author: RafaelBarbosatec<rafaelbarbosatec@gmail.com>
homepage: https://github.com/RafaelBarbosatec/hidden_drawer_menu

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

